v3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   Smoke:
-    runs-on: macos-latest
+    runs-on: self-hosted
 
     steps:
       - name: Checkout code
@@ -21,18 +21,22 @@ jobs:
         run: npm install
 
       - name: Run test case
-        run: npm run f L-01
+        id: error  # Đặt ID cho bước này để tham chiếu đến sau
+        run: npm run f L-01 || echo "Test failed"  # Lệnh chạy test, nếu lỗi thì tiếp tục
+
+      # - name: Send failure notification to Lark
+      #   if: failure()  # Chỉ chạy bước này khi job thất bại
+      #   run: node src/core/messageToLark.js "$ERROR_MESSAGE"  # Truyền lỗi vào thông báo
 
       - name: Upload test report
         uses: actions/upload-artifact@v4  # Upload report làm artifact
         with:
-          name: allure-reports  # Tên artifact (có thể tuỳ chỉnh)
-          path: |
-            allure-report
-            reports/allure-results
+          name: allure-results  # Tên artifact (có thể tuỳ chỉnh)
+          path: reports/allure-results
+          
 
   deploy_report:
-    runs-on: macos-latest
+    runs-on: self-hosted
     needs: Smoke  # Chỉ chạy sau khi Smoke thành công
 
     steps:
@@ -50,14 +54,14 @@ jobs:
       - name: Download test report
         uses: actions/download-artifact@v4
         with:
-          name: allure-reports  # Tên của artifact đã upload
+          name: allure-results  # Tên của artifact đã upload
+          path: reports/allure-results
       - name: Deploy report
         run: |
-          echo "Deploying report..."
-          cat allure-report/favicon.ico  
+          ls  ./reports
 
   send_notifications_to_lark:
-    runs-on: macos-latest
+    runs-on: self-hosted
     needs: [Smoke, deploy_report]  # Chỉ chạy sau khi Smoke và deploy_report thành công
 
     steps:
